<x-guest-layout>
    <x-wedo.pages.header :title="__('Terms of service')"></x-wedo.pages.header>

    <!-- This example requires Tailwind CSS v2.0+ -->
    <div class="max-w-7xl mx-auto px-4 py-6 sm:px-6 sm:py-8 lg:px-8 bg-white shadow sm:rounded-lg">
        <div class="px-4 py-5 sm:p-6">
            <div class="mt-2 w-full text-sm text-gray-500 whitespace-pre-line">
                <meta http-equiv="content-type" content="text/html; charset=utf-8">
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">ALLGEMEINE GESCHÄFTSBEDINGUNGEN&nbsp;</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 1 Geltungsbereich und Anbieter</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Diese Allgemeinen Geschäftsbedingungen gelten für alle Bestellungen, die Sie&nbsp;bei dem Online-Shop der&nbsp;SHOP SPAR tätigen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Das Warenangebot in unserem Online-Shop richtet sich ausschließlich an<br>Käufer, die das 18. Lebensjahr vollendet haben.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(3)</strong><span>&nbsp;</span>Unsere Lieferungen, Leistungen und Angebote erfolgen ausschließlich auf der&nbsp;Grundlage dieser Allgemeinen Geschäftsbedingungen. Die Allgemeinen Geschäftsbedingungen gelten gegenüber Unternehmen somit auch für alle künftigen Geschäftsbeziehungen, auch wenn sie nicht nochmals ausdrücklich vereinbart werden. Der Einbeziehung von Allgemeinen Geschäftsbedingungen eines Kunden, die unseren Allgemeinen Geschäftsbedingungen widersprechen, wird schon jetzt widersprochen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(4)</strong><span>&nbsp;</span>Vertragssprache ist ausschließlich deutsch.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(5)</strong><span>&nbsp;</span>Sie können die derzeit gültigen Allgemeinen Geschäftsbedingungen auf der Website&nbsp;abrufen und ausdrucken.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 2 Vertragsschluss</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Die Warenpräsentation im Online-Shop stellt keinen verbindlichen Antrag auf den Abschluss eines Kaufvertrages dar. Vielmehr handelt es sich um eine unverbindliche Aufforderung, im Online-Shop Waren zu bestellen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Mit Anklicken des Buttons [„Jetzt zahlungspflichtig bestellen“ / „kaufen“]<br>geben Sie ein verbindliches Kaufangebot ab (§ 145 BGB). Unmittelbar vor<br>Abgabe dieser Bestellung können Sie die Bestellung noch einmal überprüfen und ggf. korrigieren.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(3)</strong><span>&nbsp;</span>Nach Eingang des Kaufangebots erhalten Sie eine automatisch erzeugte E-Mail,&nbsp;mit der wir bestätigen, dass wir Ihre Bestellung erhalten haben (Eingangsbestätigung). Diese Eingangsbestätigung stellt noch keine Annahme Ihres Kaufangebots dar. Ein Vertrag kommt durch die Eingangsbestätigung noch nicht zustande.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(4)</strong><span>&nbsp;</span>Ein Kaufvertrag über die Ware kommt erst zustande, wenn wir ausdrücklich die Annahme des Kaufangebots erklären (Auftragsbestätigung) oder wenn wir die Ware – ohne vorherige ausdrückliche Annahmeerklärung – an Sie versenden. Ausnahme: bei Zahlung mit Vorkasse und PayPal erfolgt die Annahme der Bestellung unmittelbar mit Ihrer Bestellung.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 3 Preise</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Die auf den Produktseiten genannten Preise enthalten die gesetzliche<br>Mehrwertsteuer und sonstige Preisbestandteile und verstehen sich zzgl. der jeweiligen Versandkosten. Weitere Informationen zu den Versandkosten erhalten Sie auf unserer Internetseite unter [„Versandinformationen“ /<br>„Lieferbedingungen“].</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 4 Zahlungsbedingungen; Verzug</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Die Zahlung erfolgt wahlweise per:</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Rechnung per Vorkasse,<br>Nachnahme,<br>Kreditkarte,<br>Paypal oder<br>Lastschrift.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Die Auswahl der jeweils verfügbaren Bezahlmethoden obliegt uns. Wir<br>behalten uns insbesondere vor, Ihnen für die Bezahlung nur ausgewählte<br>Bezahlmethoden anzubieten, beispielweise zur Absicherung unseres<br>Kreditrisikos nur Vorkasse.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(3)</strong><span>&nbsp;</span>Bei Auswahl der Zahlungsart Vorkasse nennen wir Ihnen unsere<br>Bankverbindung in der Auftragsbestätigung. Der Rechnungsbetrag ist<br>innerhalb von 10 Tagen nach Erhalt der Auftragsbestätigung auf unser Konto zu überweisen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(4)</strong><span>&nbsp;</span>Bei Zahlung per Nachnahme wird eine zusätzliche Gebühr in Höhe von 25 EUR&nbsp;fällig, die der Zusteller vor Ort erhebt. Weitere Kosten und Steuern fallen nicht&nbsp;an.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(5)</strong><span>&nbsp;</span>Bei Zahlung per Kreditkarte wird der Kaufpreis zum Zeitpunkt der Bestellung auf Ihrer Kreditkarte reserviert (Autorisierung). Die tatsächliche Belastung Ihres Kreditkartenkontos erfolgt in dem Zeitpunkt, in dem wir die Ware an Sie versenden.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(6)</strong><span>&nbsp;</span>Bei der Bezahlung mit PayPal werden Sie im Bestellprozess auf die Webseite des Online-Anbieters PayPal weitergeleitet. Um den Rechnungsbetrag über&nbsp;PayPal bezahlen zu können, müssen Sie dort registriert sein bzw. sich erst registrieren, mit Ihren Zugangsdaten legitimieren und die Zahlungsanweisung an uns bestätigen. Nach Abgabe der Bestellung im Shop fordern wir PayPal zur Einleitung der Zahlungstransaktion auf. Weitere Hinweise erhalten Sie&nbsp; beim Bestellvorgang. Die Zahlungstransaktion wird durch PayPal unmittelbar<br>danach automatisch durchgeführt.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(7)</strong><span>&nbsp;</span>Bei Zahlung per Lastschrift haben Sie ggf. jene Kosten zu tragen, die infolge einer Rückbuchung einer Zahlungstransaktion mangels Kontodeckung oder aufgrund von Ihnen falsch übermittelter Daten der Bankverbindung entstehen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(8)</strong><span>&nbsp;</span>Geraten Sie mit einer Zahlung in Verzug, so sind Sie zur Zahlung der<br>gesetzlichen Verzugszinsen in Höhe von 5 Prozentpunkten über dem<br>Basiszinssatz verpflichtet. Für jedes Mahnschreiben, das nach Eintritt des<br>Verzugs an Sie versandt wird, wird Ihnen eine Mahngebühr in Höhe von 2,50 EUR berechnet, sofern nicht im Einzelfall ein niedrigerer bzw. höherer<br>Schaden nachgewiesen wird.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 5 Aufrechnung/Zurückbehaltungsrecht</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Ein Recht zur Aufrechnung steht Ihnen nur dann zu, wenn Ihre Gegenforderung&nbsp;rechtskräftig festgestellt worden ist, von uns nicht bestritten oder&nbsp;anerkannt wird oder in einem engen synallagmatischen Verhältnis zu unserer&nbsp;Forderung steht.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Sie können ein Zurückbehaltungsrecht nur ausüben, soweit Ihre Gegenforderung&nbsp;auf demselben Vertragsverhältnis beruht.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 6 Lieferung, Eigentumsvorbehalt</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Sofern nicht anders vereinbart, erfolgt die Lieferung der Ware von unserem Lager an die von Ihnen angegebene Adresse.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Die Ware bleibt bis zur vollständigen Zahlung des Kaufpreises unser<br>Eigentum.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(3)</strong><span>&nbsp;</span>Wir sind ausnahmsweise nicht zur Lieferung der bestellten Ware verpflichtet, wenn wir die Ware unsererseits ordnungsgemäß bestellt haben, jedoch nicht richtig oder rechtzeitig beliefert wurden (kongruentes Deckungsgeschäft). Voraussetzung ist, dass wir die fehlende Warenverfügbarkeit nicht zu vertreten haben und Sie über diesen Umstand unverzüglich informiert haben. Zudem dürfen wir nicht das Risiko der Beschaffung der bestellten Ware übernommen haben. Bei entsprechender Nichtverfügbarkeit der Ware werden wir Ihnen bereits geleistete Zahlungen unverzüglich erstatten. Das Risiko, eine bestellte Ware besorgen zu müssen (Beschaffungsrisiko), übernehmen wir nicht. Dies gilt auch bei der Bestellung von Waren, die nur ihrer Art und ihren Merkmalen nach beschrieben ist (Gattungswaren). Wir sind nur zur Lieferung<br>aus unserem Warenvorrat und der von uns bei unseren Lieferanten bestellten Waren verpflichtet.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(4)</strong><span>&nbsp;</span>Wenn Sie Unternehmer im Sinne des § 14 BGB sind, gilt ergänzend Folgendes:</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">- Wir behalten uns das Eigentum an der Ware bis zum vollständigen<br>Ausgleich aller Forderungen aus der laufenden Geschäftsbeziehung vor.<br>Vor Übergang des Eigentums an der Vorbehaltsware ist eine Verpfändung<br>oder Sicherheitsübereignung nicht zulässig.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">- Sie dürfen die Ware im ordentlichen Geschäftsgang weiterverkaufen. Für<br>diesen Fall treten Sie bereits jetzt alle Forderungen in Höhe des<br>Rechnungsbetrages, die Ihnen aus dem Weiterverkauf erwachsen, an uns<br>ab. Wir nehmen die Abtretung an, Sie sind jedoch zur Einziehung der<br>Forderungen ermächtigt. Soweit Sie Ihren Zahlungsverpflichtungen nicht<br>ordnungsgemäß nachkommen, behalten wir uns das Recht vor,<br>Forderungen selbst einzuziehen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">- Bei Verbindung und Vermischung der Vorbehaltsware erwerben wir<br>Miteigentum an der neuen Sache im Verhältnis des Rechnungswertes der<br>Vorbehaltsware zu den anderen verarbeiteten Gegenständen zum<br>Zeitpunkt der Verarbeitung.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">- Wir verpflichteten uns, die uns zustehenden Sicherheiten auf Verlangen<br>insoweit freizugeben, als der realisierbare Wert unserer Sicherheiten die<br>zu sichernden Forderungen um mehr als 10 % übersteigt. Die Auswahl der<br>freizugebenden Sicherheiten obliegt uns.</span></span></span></p>
                <p><strong>(6)</strong>&nbsp;Versand und Lieferzeiten&nbsp;</p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Wir benötigen zwischen 1-3 Tagen, um Ihre Bestellung zu bearbeiten(versenden). Nachdem Ihre Bestellung versandfertig ist, erhalten Sie von uns per E-Mail eine Versandbestätigung.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Aufgrund der hohe Anfrage kommen unsere Produkte in der Regel zwischen 14 und 21 Tagen an, können aber je nach Adresse mehr als 25 Tage bis zur Auslieferung benötigen.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 7 Widerrufsbelehrung</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Für den Fall, dass Sie Verbraucher im Sinne des<span>&nbsp;</span><strong>§ 13 BGB</strong><span>&nbsp;</span>sind, also den Kauf zu&nbsp;Zwecken tätigen, die überwiegend weder Ihrer gewerblichen noch Ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können, haben Sie ein Widerrufsrecht nach Maßgabe der folgenden Bestimmungen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>Widerrufsrecht</strong><br></span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Sie haben das Recht, binnen<span>&nbsp;</span><strong>vierzehn Tagen</strong><span>&nbsp;</span>ohne Angabe von Gründen diesen Vertrag zu widerrufen.<br>Die Widerrufsfrist beträgt<span>&nbsp;</span><strong>vierzehn Tage</strong><span>&nbsp;</span>ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz&nbsp; genommen haben bzw. hat.<br>Um Ihr Widerrufsrecht auszuüben, müssen Sie uns<br></span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Firma:<strong><span>&nbsp;SHOP SPAR</span></strong><br>Mail:&nbsp;<strong>contact@</strong></span></span></span><strong><span>shop-spar</span>.com</strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief,&nbsp;Telefax oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen,&nbsp;informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.<br>Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.</span></span></span></p>
                <p><strong>&nbsp;Folge des Widerrufsrechts</strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem<br>Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.<br>Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist.<br>Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen<span>&nbsp;</span><strong>vierzehn Tagen</strong><span>&nbsp;</span>ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrags unterrichten, an uns oder an [ggf. Name und Anschrift einer von Ihnen zur Entgegennahme der Ware berechtigten Person] zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden.<br>Sie tragen die unmittelbaren Kosten der Rücksendung der Waren.<br>Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.&nbsp;</span></span></span></p>
                <p><span><strong>Muster-Widerrufsformular</strong></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es uns per E-Mail zurück An:<span>&nbsp;</span><strong>contact@rettiflex.com</strong></span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><br>Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*):<br>Bestellt am (*)/erhalten am (*)<br>Name des/der Verbraucher(s):<br>Anschrift des/der Verbraucher(s):<br>Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier)<br>Datum<br>(*) Unzutreffendes streichen.<br><br><strong>Ende der Widerrufsbelehrung</strong></span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Das Widerrufsrecht besteht nicht bei der Lieferung<br></span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>-</strong><span>&nbsp;</span>von Waren, die nicht vorgefertigt sind und für deren Herstellung eine<br>individuelle Auswahl oder Bestimmung durch den Verbraucher<br>maßgeblich ist oder die eindeutig auf die persönlichen Bedürfnisse des<br>Verbrauchers zugeschnitten sind (z. B. T-Shirts mit Ihrem Foto und Ihrem<br>Namen),<br><strong>-</strong><span>&nbsp;</span>versiegelter Waren, die aus Gründen des Gesundheitsschutzes oder der<br>Hygiene nicht zur Rückgabe geeignet sind, wenn ihre Versiegelung nach<br>der Lieferung entfernt wurde,<br><strong>-</strong><span>&nbsp;</span>von Waren, wenn diese nach der Lieferung auf Grund ihrer Beschaffenheit untrennbar mit anderen Gütern vermischt wurden,<br><strong>-</strong><span>&nbsp;</span>von Ton- oder Videoaufnahmen oder Computersoftware in einer<br>versiegelten Packung, wenn die Versiegelung nach der Lieferung entfernt<br>wurde,<br><strong>-</strong><span>&nbsp;</span>von Zeitungen, Zeitschriften oder Illustrierten mit Ausnahme von<br>Abonnement-Verträgen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>-</strong><span>&nbsp;</span>Von Waren, die Sie schon benutzt haben. Dies gilt nur für Artikel, die für die körperliche Hygiene oder Pflege benutzt werden.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Bitte vermeiden Sie Beschädigungen und Verunreinigungen. Senden Sie die Ware bitte möglichst in Originalverpackung mit sämtlichem Zubehör und mit allen Verpackungsbestandteilen an uns zurück. Verwenden Sie ggf. eine schützende Umverpackung. Wenn Sie die Originalverpackung nicht mehr besitzen, sorgen Sie bitte mit einer geeigneten Verpackung für einen ausreichenden Schutz vor Transportschäden, um Schadensersatzansprüche wegen Beschädigungen infolge mangelhafter Verpackung zu vermeiden.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(3)</strong><span>&nbsp;</span>Bitte schreiben Sie uns vor der Rücksendung eine E-Mail an<span>&nbsp;</span><strong>contact@rettiflex.com</strong>, um die Rücksendung anzukündigen. Auf diese Weise ermöglichen Sie uns eine schnellstmögliche Zuordnung der Produkte.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(4)</strong><span>&nbsp;</span>Bitte beachten Sie, dass die in den vorstehenden Absätzen 2 und 3 genannten Modalitäten nicht Voraussetzung für die wirksame Ausübung des Widerrufsrechts sind.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 8 Transportschäden</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Werden Waren mit offensichtlichen Transportschäden angeliefert, so<br>reklamieren Sie solche Fehler bitte sofort bei dem Zusteller und nehmen Sie bitte schnellstmöglich Kontakt zu uns auf.<br><br>(2) Die Versäumung einer Reklamation oder Kontaktaufnahme hat für Ihre<br>gesetzlichen Gewährleistungsrechte keine Konsequenzen. Sie helfen uns aber, unsere eigenen Ansprüche gegenüber dem Frachtführer bzw. der<br>Transportversicherung geltend machen zu können.</span></span></span></p>
                <p>&nbsp;</p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 9 Haftung</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Unbeschränkte Haftung: Wir haften unbeschränkt für Vorsatz und grobe<br>Fahrlässigkeit sowie nach Maßgabe des Produkthaftungsgesetzes. Für leichte Fahrlässigkeit haften wir bei Schäden aus der Verletzung des Lebens, des Körpers und der Gesundheit von Personen.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Im Übrigen gilt folgende beschränkte Haftung: Bei leichter Fahrlässigkeit haften wir nur im Falle der Verletzung einer wesentlichen Vertragspflicht, deren Erfüllung die ordnungsgemäße Durchführung des Vertrags überhaupt erst ermöglicht und auf deren Einhaltung Sie regelmäßig vertrauen dürfen (Kardinalpflicht). Die Haftung für leichte Fahrlässigkeit ist der Höhe nach beschränkt auf die bei Vertragsschluss vorhersehbaren Schäden, mit deren Entstehung typischerweise gerechnet werden muss. Diese Haftungsbeschränkung gilt auch zugunsten unserer Erfüllungsgehilfen.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 10 Alternative Streitbeilegung</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3">Die EU-Kommission hat eine Plattform für außergerichtliche Streitschlichtung bereitgestellt. Verbrauchern gibt dies die Möglichkeit, Streitigkeiten im Zusammenhang mit Ihrer Online-Bestellung zunächst ohne die Einschaltung eines Gerichts zu klären. Die Streitbeilegungs-Plattform ist unter dem externen Link<br>http://ec.europa.eu/consumers/odr/ erreichbar.<br>Wir sind bemüht, eventuelle Meinungsverschiedenheiten aus unserem Vertrag einvernehmlich beizulegen. Darüber hinaus sind wir zu einer Teilnahme an einem Schlichtungsverfahren nicht verpflichtet und können Ihnen die Teilnahme an einem solchen Verfahren leider auch nicht anbieten.</span></span></span></p>
                <p><strong><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><span>§ 11 Schlussbestimmungen</span></span></span></span></strong></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(1)</strong><span>&nbsp;</span>Sollten eine oder mehrere Bestimmungen dieser AGB unwirksam sein oder werden, wird dadurch die Wirksamkeit der anderen Bestimmungen im Übrigen nicht berührt.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(2)</strong><span>&nbsp;</span>Auf Verträge zwischen uns und Ihnen ist ausschließlich deutsches Recht anwendbar unter Ausschluss der Bestimmungen der United Nations<br>Convention on Contracts for the International Sale of Goods (CISG, „UNKaufrecht“). Zwingende Bestimmungen des Landes, in dem Sie sich<br>gewöhnlich aufhalten, bleiben von der Rechtswahl unberührt.</span></span></span></p>
                <p><span color="#000000"><span face="Helvetica Neue, Helvetica, Arial, sans-serif"><span size="3"><strong>(3)</strong><span>&nbsp;</span>Sind Sie Kaufmann, juristische Person des öffentlichen Rechts oder öffentlichrechtliches&nbsp; Sondervermögen, so ist unser Geschäftssitz Gerichtsstand für alle Streitigkeiten aus oder im Zusammenhang mit Verträgen zwischen uns und Ihnen.</span></span></span></p>
            </div>
        </div>
    </div>



    <!-- Footer Section -->
    <x-wedo.home.footer></x-wedo.home.footer>
</x-guest-layout>
